services:
  lw-postgres:
    container_name: lw-postgres
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lightweight_db
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: lw-postgres
    depends_on:
      - lw-postgres

volumes:
  postgres_db:
